<?php

/**
 * AgentDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgentDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgentDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgentDetails');
    }
}