<?php

/**
 * Agents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agents extends BaseAgents {

    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }

    public function processForm() {
        if ($_POST && $this->validateForm()) {

            if ($this->agent_id) {
                Doctrine_Query::create()
                        ->delete()
                        ->from('ProductAgents')
                        ->where('agent_id=?', $this->agent_id)
                        ->execute();
                Doctrine_Query::create()
                        ->delete()
                        ->from('AgentDetails')
                        ->where('agent_id=?', $this->agent_id)
                        ->execute();
            }
            $this->agent_is_active = $_POST['agent_is_active'];
            $this->agent_order = $_POST['agent_order'];
            $this->country_id = $_POST['agent_country'];
            $this->save();

            //adding agents details
            $agentDetail = new AgentDetails();
            $agentDetail->agent_name = $_POST['agent_name'];
            $agentDetail->agent_address = $_POST['agent_address'];
            $agentDetail->agent_fax = $_POST['agent_fax'];
            $agentDetail->agent_tel = $_POST['agent_tel'];
            $agentDetail->agent_email = $_POST['agent_email'];
            $agentDetail->agent_id = $this->agent_id;

            $agentDetail->save();

            foreach ($_POST['agent_product'] as $value) {
                $prodAgent = new ProductAgents();
                $prodAgent->prod_id = $value;
                $prodAgent->agent_id = $this->agent_id;
                $prodAgent->save();
            }
            
//            save_url(URL_PREFIX_AGENTS.$this->agent_id);
            return true;
        }
        return FALSE;
    }

    private function validateForm() {
        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');

        $this->CI->form_validation->set_rules('agent_is_active', '', 'xss_clean');
        $this->CI->form_validation->set_rules('agent_name', '', 'required|xss_clean');
        $this->CI->form_validation->set_rules('agent_fax', '', 'required|numeric|xss_clean');
        $this->CI->form_validation->set_rules('agent_tel', '', 'required|numeric|xss_clean');
        $this->CI->form_validation->set_rules('agent_address', '', 'required|xss_clean');
        $this->CI->form_validation->set_rules('agent_email', '', 'required|valid_email|xss_clean');
        $this->CI->form_validation->set_rules('agent_order', '', 'required|numeric|xss_clean');
        $this->CI->form_validation->set_rules('agent_product', '', 'required|xss_clean');
        $this->CI->form_validation->set_rules('agent_country', '', 'required|select[' . lang('global_select') . ']|xss_clean');
//        if($this->agent_id){
//            validte_url(URL_PREFIX_AGENTS.$this->agent_id);
//        }else{
//            validte_url();
//        }
        return $this->CI->form_validation->run();
    }

    public function populate() {
        if (!$_POST) {
            $_POST['agent_is_active'] = $this->agent_is_active;
            $_POST['agent_order'] = $this->agent_order;
            $_POST['agent_country'] = $this->country_id;

            $agentDetail = AgentDetailsTable::getInstance()
                    ->findBySql('agent_id=? AND lang_id=?', array($this->agent_id, 1), Doctrine_Core::HYDRATE_ARRAY);
            $_POST['agent_name'] = $agentDetail[0]['agent_name'];
            $_POST['agent_fax'] = $agentDetail[0]['agent_fax'];
            $_POST['agent_tel'] = $agentDetail[0]['agent_tel'];
            $_POST['agent_address'] = $agentDetail[0]['agent_address'];
            $_POST['agent_email'] = $agentDetail[0]['agent_email'];

            $agentProducts = ProductAgentsTable::getInstance()
                    ->findBySql('agent_id=?', array($this->agent_id), Doctrine_Core::HYDRATE_ARRAY);
            foreach ($agentProducts as $value) {
                $_POST['agent_product'][] = $value['prod_id'];
            }
//            populate_url(URL_PREFIX_AGENTS.$this->agent_id);
            $this->CI->process_form = false;
            $this->validateForm();
        }
    }

    public function delete(Doctrine_Connection $conn = null) {
        parent::delete($conn);
//        delete_url(URL_PREFIX_AGENTS.$this->agent_id);
    }
}