<?php

/**
 * AgentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgentsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object AgentsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Agents');
    }

    public static function getAgents($prod_id = '', $countr_id = '') {
        $q = Doctrine_Query::create()
                ->select()
                ->from('
                    Agents a,
                    a.AgentDetails ad,
                    a.Countries c,
                    a.ProductAgents pa,
                    pa.Products p,
                    p.ProductDetails pd')
                ->where('ad.lang_id=?', 1)
                ->andWhere('pd.lang_id=?', get_language_id());

        if ($prod_id) {
            $q->andWhere('p.prod_id=?', $prod_id);
        }
        if ($countr_id) {
            $q->andWhere('c.country_id=?', $countr_id);
        }

        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->orderBy('country_id , agent_order ASC')
                        ->execute();
    }

}