<?php

/**
 * ArticlesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticlesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ArticlesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Articles');
    }

    public static function getNews() {

        $q = Doctrine_Query::create()
                ->from('Articles')
                ->orderBy('news_created_at DESC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);

        return $q->execute();
    }

    public static function getLatestNews() {
        $q = Doctrine_Query::create()
                ->from('Articles a,a.NewsDetails nd')
                ->orderBy('news_created_at DESC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->andWhere('nd.lang_id=?',  get_language_id());
        $q->andWhere('news_is_active=?', 1)
                ->limit(LATEST_NEWS_LIMIT);
        return $q->execute();
    }

}