<?php

/**
 * BannersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banners');
    }
    
    public static function getBanners($type='banner'){
        
        $q=  Doctrine_Query::create()
                ->from('Banners')
                ->orderBy('banner_order ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        $q->where('banner_type=?',$type);
        return $q->execute();
    }
    
    public static function getHomeBanners(){
        $q=  Doctrine_Query::create()
                ->from('Banners')
                ->orderBy('banner_order ASC')
                ->limit(5)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        $q->where('banner_type=?','banner');
        $q->andWhere('banner_scope="HOME" OR banner_scope LIKE ""');
        $q->andWhere('banner_is_active=1');
        return $q->execute();
    }
}