<?php

/**
 * Countries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @property My_Controller $CI
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Countries extends BaseCountries
{

    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }
    public function processForm() {
        if ($_POST && $this->validateForm()) {
            $this->country_name = $_POST['country_name'];
            $this->country_logo = $_POST['country_logo'];
            $this->save();
            return true;
        }
        return false;
    }
    private function validateForm() {
        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');
        if(!$this->country_id){
            $this->CI->form_validation->set_rules('country_name', '', 'required|unique[CountriesTable,checkUnique]|xss_clean');
        }else{
            $this->CI->form_validation->set_rules('country_name', '', 'required|unique[CountriesTable,checkUnique,country_id,'.$this->country_id.']|xss_clean');
        }
        $this->CI->form_validation->set_rules('country_logo', '', 'xss_clean');
        
        return $this->CI->form_validation->run();
    }

    public function populate() {
        if (!$_POST) {
            $_POST['country_name'] = $this->country_name;
            $_POST['country_logo'] = $this->country_logo;
            
            $this->CI->process_form = false;
            $this->validateForm();
        }
    }
}