<?php

/**
 * ProductDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Details extends Doctrine_Table {
    
    public static function getDetail($model,$key,$key_value, $lang_code = "") {
        $q = Doctrine_Query::create()
                ->select('md.*')
                ->from("$model md,md.Languages l")
                ->where("md.$key=?", $key_value);
        
        if($lang_code!='')
            $q->andWhere('l.lang_code=?', $lang_code);
            
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getList($model,$order_by='',$key='',$key_value='',$lang_id = '',$with_details=false) {

        $q = Doctrine_Query::create()
                ->select()
                ->from("$model m");
        if ($lang_id)
            $q->where('md.lang_id =?', $lang_id);
        if($with_details){
            $detailName=trim($model,'s');
            $q->leftJoin("m.$detailName md");
        }
        if($key)
            $q->andWhere("m.$key=?",$key_value);
        
        $q->orderBy("m.$order_by ASC");
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->execute();
    }
}
