<?php

/**
 * FaqDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqDetails');
    }
}