<?php

/**
 * Faqs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Faqs extends BaseFaqs
{
    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }
    
    public function processForm() {
        if ($_POST && $this->validateForm()) {
            if(isset($_POST['faq_is_active'])){
                $this->faq_is_active = $_POST['faq_is_active'];
            }
            $this->faq_order=  $_POST['faq_order'];
            $this->save();

            foreach (get_lang_list() as $key => $lang) {
                $language = LanguagesTable::getLanguage($key);
                $faqDetails = FaqDetailsTable::getInstance()
                        ->findBySql('faq_id =? AND lang_id=?', array($this->faq_id, $language['lang_id']));

                $faqDetail = $faqDetails[0];
                $faqDetail->faq_id = $this->faq_id;
                $faqDetail->faq_question = $_POST['faq_question_' . $key];
                $faqDetail->faq_answer = $_POST['faq_answer_' . $key];
                $faqDetail->lang_id = $language['lang_id'];
                $faqDetail->save();
            }

            return true;
        }

        return FALSE;
    }

    private function validateForm() {

        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');
        foreach (get_lang_list() as $key => $lang) {
            $this->CI->form_validation->set_rules("faq_question_$key", "", "required|xss_clean");
            $this->CI->form_validation->set_rules("faq_answer_$key", "", "required");
        }

        $this->CI->form_validation->set_rules("faq_is_active", "", "xss_clean");
        $this->CI->form_validation->set_rules("faq_order", "", "required|numeric|xss_clean");

        return $this->CI->form_validation->run();
    }

    public function populateForm() {
        if (!$_POST) {
            foreach (get_lang_list() as $key => $lang) {
                $language = LanguagesTable::getLanguage($key);
                $faqDetail = FaqDetailsTable::getInstance()->
                        findBySql(
                        'faq_id =? AND lang_id=?', array($this->faq_id,
                    $language['lang_id']), Doctrine_Core::HYDRATE_ARRAY);

                $_POST["faq_question_$key"] = $faqDetail[0]['faq_question'];
                $_POST["faq_answer_$key"] = $faqDetail[0]['faq_answer'];
            }

            $_POST["faq_is_active"] = $this->faq_is_active;
            $_POST["faq_order"] = $this->faq_order;
            $this->CI->process_form = false;
            $this->validateForm();
        }
    }
}