<?php

/**
 * FaqsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object FaqsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Faqs');
    }

    public static function getFaqs($active_only = false, $with_details = false) {
        $q = Doctrine_Query::create()
                ->from('Faqs f')
                ->orderBy('faq_order ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        if ($active_only)
            $q->where('faq_is_active=1');

        if ($with_details) {
            $q->leftJoin('f.FaqDetails fd')
                    ->andWhere('lang_id=?', get_language_id());
        }

        return $q->execute();
    }

}