<?php

/**
 * FeedbacksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedbacksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedbacksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Feedbacks');
    }
}