<?php

/**
 * JobsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object JobsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Jobs');
    }

    public static function getJobs($lang_id = '', $with_details = false, $active_only = false) {

        $q = Doctrine_Query::create()
                ->select()
                ->from('Jobs j');
        if ($lang_id)
            $q->where('jd.lang_id =?', $lang_id);

        if ($with_details)
            $q->leftJoin('j.JobDetails jd');

        if ($active_only)
            $q->andWhere('j.job_is_active =?', 1);

        $q->orderBy('j.job_order ASC');
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->execute();
    }

    public static function getJob($job_id) {

        $q = Doctrine_Query::create()
                ->select()
                ->from('Jobs j')
                ->andWhere('j.job_id=?', $job_id);
        $q->where('jd.lang_id =?', get_language_id());
        $q->leftJoin('j.JobDetails jd');
        $q->orderBy('j.job_order ASC');
        
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->fetchOne();
    }

}