<?php

/**
 * MediaContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediaContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MediaContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MediaContacts');
    }
    
    public static function getAllMediaContacts($lang_id = 1){
        return Doctrine_Query::create()
                ->select('mc.*, pd.prod_title')
                ->from('ProductDetails pd, pd.MediaContacts mc')
                ->where('pd.lang_id=?', $lang_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}