<?php

/**
 * MediaContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MediaContacts extends BaseMediaContacts
{
    public function addMediaContact(array $data){
        $c = new MediaContacts();
        $c->product_details_id = $data['product_details_id'];
        $c->email = $data['email'];
        $c->created_at = date('ymdHis');
        $c->save();
    }
}