<?php

/**
 * NewsDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsDetails');
    }
    
    public static function gelAllNews($type = 1, $lang_id = 1){
        return Doctrine_Query::create()
                ->select('n.*')
                ->from('NewsDetails n,n.Articles a')
                ->where('n.lang_id=?', $lang_id)
                ->andWhere('n.news_type=?', $type)
                ->andWhere('a.news_is_active=1')
                ->orderBy('news_created_at DESC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getNewsCount($type = 1){
        return (int)Doctrine_Query::create()
                ->select('count(*)/2')
                ->from('NewsDetails n,n.Articles a')
                ->andWhere('n.news_type=?', $type)
                ->andWhere('a.news_is_active=1')
                ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
                ->execute();
    }
}