<?php

/**
 * PagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pages');
    }
    
    public static function getPageData($slug){
        $q=  Doctrine_Query::create()
                ->select('pd.page_content as content,pd.page_title as title,pd.page_id')
                ->from('PageDetails pd,pd.Pages')
                ->where('lang_id=?',  get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        if(is_numeric($slug)){
            $q->andWhere('pd.page_id=?',$slug);
        }else{
            $q->andWhere('slug=?',$slug);
        }
        return $q->fetchOne();
    }
    
    public static function getPagesTitles(){
        $q=  Doctrine_Query::create()
                ->select('pd.page_title,p.slug')
                ->from('PageDetails pd,pd.Pages p')
                ->where('lang_id=?',  get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        
        $results=$q->execute();
//        pre_print($results);  
        $titles=array();
        foreach ($results as $value) {
            $titles[$value['Pages']['slug']]=$value['page_title'];
        }
        
        return $titles;
    }
}