<?php

/**
 * PageImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PageImages extends BasePageImages {

    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }

    public function processForm($page_id) {
        if ($_POST && $this->validateForm()) {
            $this->image_path = $_POST['image_path'];
            $this->image_is_active = 1;
            $this->image_order = $_POST['image_order'];
            $this->page_id=$page_id;
            $this->save();

            return true;
        }

        return FALSE;
    }

    private function validateForm() {

        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');

        $this->CI->form_validation->set_rules("image_order", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("image_path", "", "required|xss_clean");

        return $this->CI->form_validation->run();
    }

}