<?php

/**
 * PageDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageDetails');
    }
}