<?php

/**
 * PdfDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PdfDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PdfDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PdfDetails');
    }
}