<?php

/**
 * ProductDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductDetailsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductDetailsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductDetails');
    }

    public static function getProductDetail($prod_id, $lang_code = "") {
        $q = Doctrine_Query::create()
                ->select('pd.*')
                ->from('ProductDetails pd,pd.Languages l')
                ->where('pd.prod_id=?', $prod_id);
        
        if($lang_code!='')
            $q->andWhere('l.lang_code=?', $lang_code);
            
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getProductsForCountry($country_id){
        
        return Doctrine_Query::create()
                ->select('pd.*')
                ->from('ProductDetails pd,pd.Products p,p.ProductAgents pa')
                ->innerJoin('pa.Agents a')
                ->andWhere('pd.lang_id=?',  get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute()
                ;
    }

}