<?php

/**
 * ProductTabsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTabsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductTabsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductTabs');
    }
    
    public static function getTabs($prod_id,$lang_id = '',$with_details=false,$active_only=false) {

        $q = Doctrine_Query::create()
                ->select()
                ->from('ProductTabs t');
        
        if($with_details)
            $q->leftJoin('t.TabDetails td');
        if ($lang_id)
            $q->where('td.lang_id =?', $lang_id);
        if($active_only){
            $q->andWhere('t.tab_is_active=1');
        }
        $q->andWhere('prod_id=?',$prod_id);
        $q->orderBy('t.tab_order ASC');
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->execute();
    }
    
}