<?php

/**
 * ProductPdfsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPdfsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductPdfsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductPdfs');
    }

    public static function getAllProductPDFs($product_id, $lang_id = 1, $tab_id = '') {
        $q = Doctrine_Query::create()
                ->select('p.*, d.pdf_title')
                ->from('ProductPdfs p, p.PdfDetails d')
                ->where('p.prod_id=?', $product_id)
                ->andWhere('d.lang_id=?', $lang_id)
                ->orderBy('p.pdf_order  ASC')
                ->andWhere('p.pdf_is_active=1')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        if ($tab_id)
            $q->andWhere('p.tab_id=?', $tab_id);
        else
            $q->andWhere('p.tab_id IS NULL');
        return $q->execute();
    }

}