<?php

/**
 * ProductTabs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductTabs extends BaseProductTabs
{
    
    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }
    
    public function processForm($prod_id) {
        if ($_POST && $this->validateForm()) {
            $this->tab_order = $_POST['tab_order'];
            $this->tab_is_active = $_POST['tab_is_active'];
            $this->prod_id=$prod_id;
            $this->save();
            
            foreach (get_lang_list() as $key => $lang) {
                $language = LanguagesTable::getLanguage($key);
                $tabDetails = TabDetailsTable::getInstance()
                        ->findBySql('tab_id =? AND lang_id=?', array($this->tab_id,$language['lang_id']));
                
                $tabDetail=$tabDetails[0];
                $tabDetail->tab_id = $this->tab_id;
                $tabDetail->tab_title = $_POST['tab_title_' . $key];
                $tabDetail->tab_description = $_POST['tab_description_' . $key];
                $tabDetail->lang_id = $language['lang_id'];
                $tabDetail->save();
            }
            save_url(URL_PREFIX_PRODUCT_TAB_VIEW.$this->tab_id);
            return true;
        }

        return FALSE;
    }
    
    private function validateForm() {

        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');
        foreach (get_lang_list() as $key => $lang) {
            $this->CI->form_validation->set_rules("tab_title_$key", "", "required|xss_clean");
            $this->CI->form_validation->set_rules("tab_description_$key", "", "required");
        }
        if($this->prod_id){
            validte_url(URL_PREFIX_PRODUCT_TAB_VIEW.$this->tab_id);
        }else{
            validte_url();
        }
        $this->CI->form_validation->set_rules("tab_order", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("tab_is_active", "", "xss_clean");

        return $this->CI->form_validation->run();
    }
    
    
    public function populateForm() {
        if (!$_POST) {
            foreach (get_lang_list() as $key => $lang) {
                $language = LanguagesTable::getLanguage($key);
                $tabDetail = TabDetailsTable::getInstance()->
                        findBySql(
                                'tab_id =? AND lang_id=?', array($this->tab_id,
                                $language['lang_id']),
                                Doctrine_Core::HYDRATE_ARRAY);
                
                $_POST["tab_title_$key"] = $tabDetail[0]['tab_title'];
                $_POST["tab_description_$key"] = $tabDetail[0]['tab_description'];
            }
            
            $_POST["tab_order"] = $this->tab_order;
            $_POST["tab_is_active"] = $this->tab_is_active;
            populate_url(URL_PREFIX_PRODUCT_TAB_VIEW.$this->tab_id);
            $this->CI->process_form = false;
            $this->validateForm();
        }
    }
    
     public function delete(Doctrine_Connection $conn = null) {
        parent::delete($conn);
        delete_url(URL_PREFIX_PRODUCT_TAB_VIEW.$this->tab_id);
    }
}