<?php

/**
 * ProductAgentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductAgentsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductAgentsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductAgents');
    }

    public static function getAgentsForProduct($prod_id, $country_id) {
        $q = Doctrine_Query::create()
                ->select('ad.*,a.agent_id,c.country_name')
                ->from('AgentDetails ad,ad.Agents a,a.ProductAgents pa,a.Countries c')
                ->where('pa.prod_id=?', $prod_id)
                ->andWhere('a.country_id=?', $country_id)
                ->andWhere('ad.lang_id=?', get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        
        return $q->execute();
    }
    
    
    public static function getAgentsForCountry($country_id) {
        $q = Doctrine_Query::create()
                ->select('ad.*,a.agent_id,c.country_name,pa.prod_id,p.prod_id,pd.prod_title')
                ->from('AgentDetails ad,ad.Agents a,a.ProductAgents pa,a.Countries c,pa.Products p,p.ProductDetails pd')
                ->andWhere('a.country_id=?', $country_id)
                ->andWhere('a.agent_is_Active=1')
                ->andWhere('ad.lang_id=?', get_language_id())
                ->andWhere('pd.lang_id=?', get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        
        return $q->execute();
    }
    
    

}