<?php

/**
 * ProductImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductImages');
    }
    
    public static function getImages($prod_id,$limit='',$active_only=false) {

        $q = Doctrine_Query::create()
                ->select()
                ->from('ProductImages m');
        
        $q->andWhere('prod_id=?',$prod_id);
        $q->orderBy('m.image_order ASC');
        if($limit)
            $q->limit ($limit);
        if($active_only)
            $q->andWhere ('image_is_active=?',1);
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                        ->execute();
    }
}