<?php

/**
 * ProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Products');
    }

    public static function getProducts($lang_id = '',$with_details=false,$active_only=false, $count_tabs = false) {

        $q = Doctrine_Query::create()
                ->select()
                ->from('Products p');
        if ($lang_id)
            $q->where('pd.lang_id =?', $lang_id);
        
        if($with_details)
            $q->leftJoin('p.ProductDetails pd');
        
        if($count_tabs)
            $q->leftJoin(' p.ProductTabs pt');
        
        if($active_only)
            $q->andWhere('p.prod_is_active =?', 1);
        
        return $q->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->orderBy('p.prod_order')
                        ->execute();
    }

}