<?php

/**
 * ShowroomsLocations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShowroomsLocations extends BaseShowroomsLocations {

    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }

    public function addShowroomLocation(array $data) {
        if ($this->validateForm()) {
            $s = new ShowroomsLocations();
            $s->name = $data['name'];
            $s->address = $data['address'];
            $s->tel = $data['tel'];
            $s->fax = $data['fax'];
            $s->longitude = $data['longitude'];
            $s->latitude = $data['latitude'];
            $s->save();
            return true;
        }
        return false;
    }

    public function validateForm() {
        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');

        $this->CI->form_validation->set_rules("name", "", "required|xss_clean");
        $this->CI->form_validation->set_rules("address", "", "required|xss_clean");
        $this->CI->form_validation->set_rules("tel", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("fax", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("longitude", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("latitude", "", "required|numeric|xss_clean");

        return $this->CI->form_validation->run();
    }

    public function deleteShowroom($id) {
        Doctrine_Query::create()
                ->delete('ShowroomsLocations srl')
                ->where('srl.id=?', $id)
                ->execute();
    }

}