<?php

/**
 * ShowroomsLocationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShowroomsLocationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShowroomsLocationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShowroomsLocations');
    }
    
    public static function getAllShowroomsLocations(){
        return Doctrine_Query::create()
                ->select('sl.*')
                ->from('ShowroomsLocations sl')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}