<?php

/**
 * ShowroomsLocations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShowroomsLocations extends BaseShowroomsLocations {

    var $CI;

    public function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
        $this->CI = get_instance();
    }

    public function addShowroomLocation(array $data) {
        if ($this->validateForm()) {
            $this->name = $data['name'];
            $this->address = $data['address'];
            $this->tel = $data['tel'];
            $this->fax = $data['fax'];
            $this->longitude = $data['longitude'];
            $this->latitude = $data['latitude'];
            $this->location_order = $data['location_order'];
            $this->is_active = $data['is_active'];
            $this->save();
            return true;
        }
        return false;
    }

    public function validateForm() {
        $this->CI->form_validation->set_error_delimiters('<span class="frm_error_msg">', '</span>');

        $this->CI->form_validation->set_rules("name", "", "required|xss_clean");
        $this->CI->form_validation->set_rules("address", "", "required|xss_clean");
        $this->CI->form_validation->set_rules("tel", "", "numeric|xss_clean");
        $this->CI->form_validation->set_rules("fax", "", "numeric|xss_clean");
        $this->CI->form_validation->set_rules("longitude", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("latitude", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("location_order", "", "required|numeric|xss_clean");
        $this->CI->form_validation->set_rules("is_active", "", "required|xss_clean");

        return $this->CI->form_validation->run();
    }
    
    public function populate(){
        $_POST['name']=  $this->name;
        $_POST['address']=  $this->address;
        $_POST['tel']=  $this->tel;
        $_POST['fax']=  $this->fax;
        $_POST['longitude']=  $this->longitude;
        $_POST['latitude']=  $this->latitude;
        $_POST['location_order']=  $this->location_order;
        $_POST['is_active']=  $this->is_active;
        $this->validateForm();
    }

    public function deleteShowroom($id) {
        Doctrine_Query::create()
                ->delete('ShowroomsLocations srl')
                ->where('srl.id=?', $id)
                ->execute();
    }

}