<?php

/**
 * ShowroomsLocationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShowroomsLocationsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ShowroomsLocationsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ShowroomsLocations');
    }

    public static function getAllShowroomsLocations($active_only = false) {
        $q = Doctrine_Query::create()
                ->select('sl.*')
                ->from('ShowroomsLocations sl')
                ->orderBy('location_order')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
        if ($active_only)
            $q->andWhere('is_active=1');
        return $q->execute();
    }

}