<?php

/**
 * TabDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TabDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TabDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TabDetails');
    }
    public static function getTabTitle($tab_id){
        
        return Doctrine_Query::create()
                ->select('tab_title')
                ->from('TabDetails')
                ->where('tab_id =?',$tab_id)
                ->andWhere('lang_id=?',  get_language_id())
                ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
                ->execute();
    }
}