<?php

/**
 * UrlsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UrlsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UrlsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Urls');
    }
    
    public static function checkUrl($url_routed,$url_original=''){
        
        return Doctrine_Query::create()
                ->select('url_routed')
                ->from('Urls')
                ->where('url_routed=?',$url_routed)
                ->andWhere('url_original!=?', $url_original)
//                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
}